### ISSUE TITLE
Menus

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/nextjs-wordpress-starter#4]
Add support for WordPress menus.

https://docs.wpgraphql.com/getting-started/menus/#queries

Example query to get the "Primary" menu::

```graphql
query MyQuery {
  menu(id: "bmF2X21lbnU6Ng==") {
    name
    menuItems {
      edges {
        node {
          url
          label
        }
      }
    }
  }
}

```

**Comment by salcode** [comment]
I just opened #16 to update to the latest version of WP GraphQL (`0.12.1`) because it includes support for the `locations` field in the menus query.

![image](https://user-images.githubusercontent.com/5194588/91634908-26141900-e9c2-11ea-9fae-e474928562fb.png)

Once we have the `locations` field available, we should be able to map our menu data to each location (e.g. we could use `menus.primary` to access the menu information for the **primary** location). 🎉
