### ISSUE TITLE
Form Handling

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/nextjs-wordpress-starter#45]
Create a connection between Gravity Forms in WordPress and [Formik](https://github.com/formium/formik)

**Requirements**

- [x] User creates a form in WordPress, and drops it into a page via Gutenberg
- [ ] Front-end queries the page (already done) and displays the form via Formik
- [ ] Each field from Gravity Forms needs to be matched up with Formik
- [ ] Submissions need to go back into WordPress (partner w/ @ravewebdev on this)

**Comment by michealengland** [comment]
## Updates 12/28 & 12/29
I did some research on how to integrate this feature and paired up with @ravewebdev on getting some of the infrastructure setup.

Here is what I have in place so far

1. Formik will be our primary form solution for handling field input state, validation, and overall form experiences. 
2. We're using Yup for field validation so that we can easily define requirements on fields. See demo below.
3. Currently, we're using [wp-graphql-gravity-forms ](https://github.com/harness-software/wp-graphql-gravity-forms) to get GravityForm data from the Rest Endpoint in GraphiQL
4.  I have a structure in place for how we'll handle GravityForm fields.

## Handling GravityForm Fields
- Block level component `Block/BlockGravityForms` which handles mapping block data to the Form component
- Form molecule component is a generic form in charge of handling input state, form submissions, and rendering fields.
- The `GravityFormFields` takes field data from the block and loops through each field input.
- Each field will get mapped to a GravityForms field component (named after the type) which will map props to an input. For now this structure looks like the following Ex: `<Field.Text />`.

## Challenges

There are still some challenges around the following areas that are in progress of being solved
- Setting up validation per GravityForm field. This is easy on a custom field, but will require some craftiness.
- Putting a list of starting GF Fields to focus on. Due to the amount of fields and form settings this is something that will need to be iterated on.
- Form submissions will require some research

## Demos
Example of Yup in progress
![Dec-29-2020 14-01-18](https://user-images.githubusercontent.com/25035900/103326286-abb1df00-4a1d-11eb-9cb1-faff77349a6a.gif)

<img width="666" alt="Screen Shot 2020-12-29 at 5 50 53 PM" src="https://user-images.githubusercontent.com/25035900/103326290-af456600-4a1d-11eb-9d40-016e62d80a1b.png">

**Comment by michealengland** [comment]
I got a lot features ready and have setup a draft PR for this ticket.

See https://github.com/WebDevStudios/nextjs-wordpress-starter/pull/53

**Comment by michealengland** [comment]
## Status Updates
Basic form support and Text field support have been setup. See #53 for details around what was included in that setup.

From here there is a new direction course that we can focus on.
1. [ ] Refactor dynamic validation into a class. This feature is quiet large and will need to utilize various Yup schema types. The way it's setup now will not scale well as we build out more fields.
2. [ ] Begin work on adding more fields. Since the layout / structure is in place more fields need to be intregrated.
3. [ ] Wire up additional GF form settings. 
4. [ ] Wire up the GF Form submit.

**Comment by michealengland** [comment]
Closing this issue out in favor of smaller issues.
