### ISSUE TITLE
Yoast SEO

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/nextjs-wordpress-starter#9]
Need to support grabbing SEO data from Yoast, and bringing that data into posts, pages, and CPTs. The [WP GraphQL Yoast plugin](https://github.com/ashhitch/wp-graphql-yoast-seo) is installed and exposes this to GraphQL. 

An example query for a single post:

```graphql
query MyQuery {
  post(idType: DATABASE_ID, id: "12") {
    author {
      name
    }
    seo {
      metaDesc
      metaKeywords
      metaRobotsNofollow
      metaRobotsNoindex
    }
  }
}

```

Global settings query:

```graphql
query MyQuery {
  seo {
    schema {
      companyName
      logo {
        sourceUrl
      }
      siteName
      siteUrl
      wordpressSiteName
    }
    social {
      facebook {
        url
        defaultImage {
          sourceUrl(size: FULL_WIDTH)
        }
      }
    }
  }
}
```

**Comment by donmhico** [comment]
**Update**

I created a branch and started on this task - https://github.com/WebDevStudios/nextjs-wordpress-starter/tree/feature/9-Yoast-SEO

Basically what it does now is get the `seo` data for the post pages and render them as
```html
<meta name="description" content={seo.metaDesc} />
<meta
    name="robots"
    content={`${seo.metaRobotsNoindex}, ${seo.metaRobotsNofollow}`}
/>
```

**Note**
We are pulling `metaKeywords` but I didn't render them for now because based on the research I did `meta keywords` are no longer used.

References:
* https://yoast.com/meta-keywords/
* https://www.semrush.com/blog/meta-keywords/

**Question**
I'm unsure where to render the **Global Settings**. Also should I just pull them on all of the async functions in `lib/api.js` so it is readily available when needed?

cc @gregrickaby

**Comment by gregrickaby** [comment]
>I'm unsure where to render the Global Settings. 

See [&lt;Meta&gt;](https://github.com/gregrickaby/nextjs-starter/blob/main/components/common/Meta.js). It's component that's pulled into [&lt;Layout&gt;](https://github.com/gregrickaby/nextjs-starter/blob/main/components/common/Layout.js), which is used in all pages. Let me know if you have any questions.

>Also should I just pull them on all of the async functions in lib/api.js so it is readily available when needed? 

Yes, that would be fine.
